version: 2

defaults: &defaults
  working_directory: ~/working/repo
  docker:
    - image: circleci/node:12-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: ~/working
          paths:
            - repo

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/working
      - run: yarn build

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/working
      - run: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - install
